src/main/java/uk/gov/digital/ho/hocs/client/casework/dto/ComplaintCorrespondent.java, src/main/java/uk/gov/digital/ho/hocs/queue/common/ComplaintData.java, src/main/java/uk/gov/digital/ho/hocs/queue/common/ComplaintService.java, src/main/java/uk/gov/digital/ho/hocs/queue/common/CorrespondentType.java, src/main/java/uk/gov/digital/ho/hocs/queue/ukvi/UKVIComplaintData.java, src/test/java/uk/gov/digital/ho/hocs/client/casework/CaseworkClientTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/ComplaintServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/ukvi/UKVIComplaintDataTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/ukvi/UKVIComplaintServiceTest.java, src/test/resources/existingNoCorrespondent.json
**What:**
- Enables multiple correspondents to be created during case creation.
- Ensures the 'Complainant' is set as the Primary Correspondent, when provided.
- Allows case to be created with no correspondents, passed as part of the complaint.
**Why:**
- Complaints submitted by a third-party representative need to have the 'Agent' and the 'Complainant' added to the case correspondents with the Complainant always being the 'Primary'.
- Complaints about an existing complaint can be submitted without any correspondent details, so need to be able to create a case without any correspondents.
=> HOCS-2692: Create Multiple Correspondents

README.md, src/main/java/uk/gov/digital/ho/hocs/config/AppCustomProperties.java, src/main/java/uk/gov/digital/ho/hocs/queue/ukvi/UKVIComplaintQueueBuilder.java, src/main/resources/application.properties, src/test/java/uk/gov/digital/ho/hocs/queue/ukvi/UKVIComplaintQueueBuilderTest.java
- Add maxMessagesPerPoll as a property so that we can limit the number of messages read per poll.
- Set the poll delay to 10 seconds.
=> HOCS-3240 - Add maxMessagesPerPoll as a property

src/main/java/uk/gov/digital/ho/hocs/queue/ukvi/UKVIComplaintData.java, src/test/java/uk/gov/digital/ho/hocs/queue/ukvi/UKVIComplaintDataTest.java, src/test/resources/agentCorrespondent.json
Fixes an issue where the phone number of a third party representative wasn't being added to the correspondent.
=> HOCS-3646: Representative phone number added to relevant correspondent

.drone.yml
The drone pipeline build is currently failing as a result of not passing
through the `CLUSTER_NAME` into the deploy file. This is required to
ensure the certificate authority is authentic.
=> Pass-through CLUSTER_NAME to deploy steps

kube/kd/deployment.yaml, src/main/resources/application.yml
At present the pods are in a backoff state as the configuration has not
been set correctly. This change amends the configuration to enable the
build to deploy successfully.
=> Fix deployment configuration

kube/kd/deployment.yaml, src/main/resources/application.yml
We are currently not specifying the port number that the
spring application should start on. This means that the deployment
is attempting to hit 8080 but is getting connection refused as the
default is 8092.
=> Specify port number

src/main/java/uk/gov/digital/ho/hocs/queue/common/ComplaintService.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/ComplaintServiceTest.java
When a complaint comes through if there was no correspondent then the
case data was not updated with the complaint type. With all but 1 of the
complaint types correspondents are required. Complaints with
an `EXISTING` type don't have the correspondent requirement and
thus could lead to the case data not having the correct type. This
change ensures that the complaint type is always sent to the casework
service to be updated.
=> HOCS-4423: update case data with no correspondent

.drone.yml, kube/deploy.sh
At the minute we always use the latest version of the code for promoting
to different environments. While this is not an issue in normal cases,
when a change to the deployment config happens this can throw it out of
line. This change ensures that we always check the corresponding branch
out linked to the release, ensuring that we use the config from that
point in time.
This involves disabling the default clone step and adding a custom one
that for pushes uses the global DRONE_COMMIT_SHA environment variable
and VERSION for deployments. By default, if VERSION isn't applicable git
defaults to the head of the main branch on origin. We now promote the
build SHA for this service between environments instead of the build
number/ semvar tag. The semvar tagging infrastructure is still present
to …
=> HOCS-4421: use custom clone for branch sha

README.md, config/localstack/1-setup-sqs.sh, kube/kd/deployment.yaml, localDev/pushString.sh, src/main/java/uk/gov/digital/ho/hocs/aws/SqsConfiguration.java, src/main/java/uk/gov/digital/ho/hocs/aws/SqsMessageListenerContainerFactory.java, src/main/java/uk/gov/digital/ho/hocs/queue/common/QueueListener.java, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/java/uk/gov/digital/ho/hocs/clientutil/SQSSender.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/integration/AwsSqsIntegrationTestBase.java
As the service could potentially be used going forward for many types of
case creation. This change replaces the properties with a more generic
name.
=> HOCS-4278: change sqs props to generic name

kube/deploy.sh, kube/kd/deployment.yaml
At present, we have a separate 'new' queue in production that is held in
a different secret. This change points the deployment to the new secret
in production environments. This should be removed when ACP add the new
queue config to our not-production environments.
=> Repoint Production Secret

kube/deploy.sh, kube/kd/deployment.yaml
Since ACP have added the new queues to the not-production environment,
this change removes the differing not-prod/prod secret pointing in
favour of the single one.
=> HOCS-4278: repoint not-production secret

src/main/java/uk/gov/digital/ho/hocs/client/workflow/dto/CreateCaseRequest.java, src/main/java/uk/gov/digital/ho/hocs/queue/complaints/ComplaintService.java, src/test/java/uk/gov/digital/ho/hocs/client/workflow/WorkflowClientTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/complaints/ComplaintServiceTest.java
When a case is first created there is a period of time whereby the case
doing have the required data for the Workflow process to process the
case correctly. As we know at the start the complaint type and channel
this can be sent and processed. This allows us to drive the user
experience based on the case is a WebForm.
=> HOCS-4440: send through initial case data

src/main/java/uk/gov/digital/ho/hocs/queue/complaints/ComplaintService.java, src/test/java/uk/gov/digital/ho/hocs/queue/complaints/ComplaintServiceTest.java
To allow for the workflow process to detour based on WebForm cases we
need a non-modifiable field that indicates that the case came from the
service. This change adds a 'XOriginatedFrom' data value that is used to
drive process behaviour.
=> HOCS-4462: pass through originated from data

kube/deploy.sh, kube/kd/deployment.yaml, src/main/java/uk/gov/digital/ho/hocs/queue/common/BaseMessageHandler.java
Currently, `UKVI_COMPLAINTS` messages should be ignored within
production environments. This change passes this through the deployment
config.
This change also simplifies the `shouldIgnoreMessage` flag to be
calculated only on instantiation rather than every call as this is set
at initial runtime.
=> HOCS-4280: mark UKVI_COMPLAINTS as ignored in prod

kube/deploy.sh
Pass through an empty MESSAGE_IGNORED_TYPES for not prod environments as
kd templating requires it to be present but set to empty.
=> HOCS-4280: pass empty MESSAGE_IGNORED_TYPE

.drone.yml
When a new SemVer version is minted and tagged - we aren't deploying
this tag to the environments. Instead we are setting it to the Git SHA -
this is out of line with other services and confusing for the release
team.
=> HOCS-4672: pass SemVer tag to QA on release

.drone.yml, .github/workflows/label-check.yml, .github/workflows/semver.yml, README.md
This change removes the use of the old `hocs-version-bot` in favour of
new GitHub actions.
When an action happens on a PR an action is run that checks that the PR
is labeled with one of the following: `Patch`, `Minor`, or `Major`.
If one of these isn't present the PR will be blocked till one is added.
This enables us to immediately identify the scale of the change.
On an successful merge, an second action is ran that uses specified
label to update the SemVer version for the service - automatically
creating a Git Tag with that version.
This triggers a drone build that automatically deploys this new version
to the dev environments.
=> HOCS-4696: use GitHub SemVer actions

.github/workflows/semver.yml
When a GitHub job fails there is currently know way of identifying this,
this change sends a notification to a channel of our choosing to flag
that there is an issue that needs looking at.
To simplify upgrades to the action - this change pegs the version to the
latest major tag `v2` in this instance.
=> HOCS-5140: action failure slack integration

.drone.yml, build.gradle
Use the GitHub Package for the UKVI schema rather than a private facing
Artifactory instance. This will allow improved future changes that
require a publicly available package store.
=> HOCS-5180: use GHP rather than Artifactory

build.gradle
Update the `hocs-ukvi-complaint-schema` dependency to 1.1.1.
=> HOCS-4765: update schema version dependency

build.gradle, src/main/java/uk/gov/digital/ho/hocs/client/migration/casework/dto/CreateMigrationCaseRequest.java, src/main/java/uk/gov/digital/ho/hocs/client/migration/casework/dto/MigrationComplaintCorrespondent.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationData.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationService.java, src/test/java/uk/gov/digital/ho/hocs/client/migration/casework/MigrationCaseworkClientTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/migration/MigrationMessageValidatorTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/migration/MigrationServiceTest.java, src/test/resources/invalidMigrationMissingPrimaryCorrespondent.json, src/test/resources/invalidMigrationMissingRequiredFields.json, src/test/resources/validMigration.json
Extract correspondent information from migration message, add to casework request to create case with correspondents (and stage respectively).
=> HOCS 5583 - Extract correspondent information from migration message

build.gradle, src/main/java/uk/gov/digital/ho/hocs/client/migration/casework/dto/CreateMigrationCaseRequest.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/CaseAttachment.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationData.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationService.java, src/test/java/uk/gov/digital/ho/hocs/client/migration/casework/MigrationCaseworkClientTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/integration/MigrationQueueListenerIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/migration/MigrationMessageValidatorTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/migration/MigrationServiceTest.java, src/test/resources/invalidMigrationMessageMissingCaseAttachments.json, src/test/resources/validMigrationNoAdditionalCorrespondents.json, src/test/resources/validMigrationNoCaseAttachments.json, src/test/resources/validMigrationWithCaseAttachments.json, src/test/resources/validMigrationWithOptionalFieldsNull.json
Extract case attachments and add to request to casework.
Validation requires mandatory (non-null) fields for a case attachment:
- displayName
- documentPath
- documentType
Test for valid and invalid scenarios; both validation and deserialisation.
Using hocs-migration-schema 0.10.0
=> HOCS-5584: Add migration case attachments

.drone.yml, src/main/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintService.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationCaseService.java, src/main/resources/application-local.yml, src/main/resources/application.yml
As this service is deployed and driven from deployment configuration,
there is no longer a need to have two different set of identities within
the dataset.
This change pulls both of the current sets into one common one.
--- 
This is built on top of #206 to save headaches with merge conflicts and rebasing.
=> HOCS-6257: change identity properties

src/main/java/uk/gov/digital/ho/hocs/application/aspects/QueueListenerContextAspect.java, src/main/java/uk/gov/digital/ho/hocs/queue/common/MigrationQueueListener.java, src/main/java/uk/gov/digital/ho/hocs/queue/common/QueueListener.java, src/main/java/uk/gov/digital/ho/hocs/queue/common/UkviQueueListener.java, src/main/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintMessageHandler.java, src/main/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintService.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationCaseService.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationMessageHandler.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/MigrationQueueListenerTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/UkviQueueListenerTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintServiceTest.java
When setting the client context the previous solution only did this at the message service level manually.
There are several issues with this approach:
- Log lines that predate this do not have the associated correlation id.
- This should be an automated concern for logging purposes, and not manually triggered.
This change pulls the ClientContext handling into an AOP that injects on every invocation of the new QueueListener onMessageReceived method.
=> HOCS-6249: change client context use

src/main/java/uk/gov/digital/ho/hocs/domain/service/MessageLogService.java, src/main/java/uk/gov/digital/ho/hocs/entrypoint/MigrationQueueListener.java, src/main/java/uk/gov/digital/ho/hocs/entrypoint/UkviQueueListener.java
Instead of doing 2 database transactions for ignored messages, this
change reorders the listeners to first do a check and if a message is
marked to ignore then create a message log in one transaction with the
correct Status.
=> HOCS-6249: reorder ignoring messages

src/main/java/uk/gov/digital/ho/hocs/application/MessageContext.java
MDC handles itself in thread isolation, the previous instantiation would only have instantiated for the starting thread, thus resulting in null being passed through the stack in subsequent results. This change pulls the value into a Map that is instantiated in the initialiseContext method.
=> HOCS-6402: fix MessageContext instantiation

src/main/java/uk/gov/digital/ho/hocs/domain/repositories/MessageLogRepository.java, src/main/java/uk/gov/digital/ho/hocs/domain/service/MessageLogService.java, src/main/java/uk/gov/digital/ho/hocs/domain/service/ProcessingService.java, src/main/java/uk/gov/digital/ho/hocs/entrypoint/ProcessingController.java, src/test/java/uk/gov/digital/ho/hocs/domain/services/ProcessingServiceTest.java
The count and get of the MessageLogRepository where incorrectly returning messages that completed was before or between inputted dates. This should be retrieved.
=> HOCS-6402: fix MessageLog repository method

src/main/java/uk/gov/digital/ho/hocs/client/migration/casework/dto/CreateMigrationCaseRequest.java, src/main/java/uk/gov/digital/ho/hocs/domain/queue/migration/MigrationData.java, src/main/java/uk/gov/digital/ho/hocs/domain/queue/migration/MigrationService.java, src/test/java/uk/gov/digital/ho/hocs/client/migration/casework/MigrationCaseworkClientTest.java, src/test/java/uk/gov/digital/ho/hocs/domain/queue/migration/MigrationServiceTest.java
Changes to allow migratedReference to be propagated through to casework
=> HOCS-5649: support searches for migrated cases
