UKHomeOffice/hocs-case-creator

.drone.yml, build.gradle
This just builds the project and runs some tests.
We don't do any Docker related tasks yet.
=> HOCS-2645 Add basic Drone pipeline

src/main/java/uk/gov/digital/ho/hocs/queue/ukvi/UKVIComplaintValidator.java
The app failed to read the schema when run in Docker. This changes the file load to work locally and from the jar file.
=> HOCS-2527 : Fix the reading of the schema when run from jar file.

src/main/java/uk/gov/digital/ho/hocs/aws/LocalStackConfiguration.java, src/main/java/uk/gov/digital/ho/hocs/config/AWSCustomConfig.java, src/main/java/uk/gov/digital/ho/hocs/queue/ukvi/UKVIComplaintValidator.java
I removed this, forgetting it was need in the docker-compose. Reinstated.
=> hocs 2527 reinstate localstack hostname

.gitignore, build.gradle, src/main/resources/cmsSchema.json
A local docker build works fine, the image from quay can't find the schema!
As we are moving to a real dependancy, this is move back to fixed in the short term.
=> HOCS-2527 : Move to fixed schema, waiting for real dependancy.

.drone.yml
Remove the unneeded step to deploy to WCS-DEV
=> HOCS-3245 - Remove deploy to WCS

src/main/java/uk/gov/digital/ho/hocs/client/audit/AuditClient.java
=> HOCS-3545 - correct userId logging

src/main/java/uk/gov/digital/ho/hocs/queue/ukvi/UKVIComplaintValidator.java, src/test/java/uk/gov/digital/ho/hocs/queue/ukvi/UKVIComplaintValidatorTest.java, src/test/resources/notJson.txt
Audit non-json validation errors
=> HOCS-3546 - Catch non json validation errors

src/main/java/uk/gov/digital/ho/hocs/queue/common/ComplaintService.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/ComplaintServiceTest.java
Complaint cases should only be auto advanced as far as Complainant Details stage
=> HOCS-3522 Start cases at correct stage

Dockerfile, build.gradle, scripts/run.sh, src/main/resources/application.properties
Atomic commits for 
* Multi stage docker build with layered jars
* Spring context indexer
* Disable unused actuator endpoints
=> Hocs 4073 docker best practice

gradle/wrapper/gradle-wrapper.properties, src/test/java/uk/gov/digital/ho/hocs/queue/ukvi/integration/BaseAwsSqsIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/ukvi/integration/UKVIComplaintQueueTest.java
Hocs-4376: Upgrade Gradle version to support JDK 17
=> Hocs-4376: Upgrade Gradle version to support JDK 17

.drone.yml
We are currently using a version of KD that is 2 years old. This change
brings this upto date and uses the latest released version.
=> HOCS-4421: update KD version

README.md
Remove redundant information within the README, add standard sections
and correct Java version.
=> Docs: Improve README.md

src/main/java/uk/gov/digital/ho/hocs/queue/common/MessageTypes.java, src/main/java/uk/gov/digital/ho/hocs/queue/common/MigrationQueueListener.java, src/main/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintData.java, src/main/java/uk/gov/digital/ho/hocs/queue/data/CaseData.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationCaseService.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationCaseTypeData.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationData.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationMessageHandler.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationService.java, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/java/uk/gov/digital/ho/hocs/queue/common/ConditionalBeanTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/MessageTypes.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/MigrationQueueListenerTest.java
[HOCS-5148] Same as PR https://github.com/UKHomeOffice/hocs-case-creator/pull/141/
Creating a new PR due to some Merge Inconsistencies.
Added new Migration Message Handler to handle message from Migration Queue of type Migrated-Cases.
Added new MigrationQueueListener @ConditonalOnProperty, Updated QueueListener to handle MigrationEvent
Added new messageType MIGRATED-CASES
Added unit tests to check the new message type, Conditional Bean for QueueListener
Added a place holder for Migration Service and we will add code to Store untrusted S3 Object, Document Summary and Create workflow for Migrated Case.
=> HOCS-5148 Consume from Migration Queue

.drone.yml
JIRA LINK : https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-5305
=> HOCS-5305: Add deployment step for cs-prod-migration

build.gradle, src/main/java/uk/gov/digital/ho/hocs/client/casework/CaseworkClient.java, src/main/java/uk/gov/digital/ho/hocs/client/casework/dto/CreateCaseworkCaseResponse.java, src/main/java/uk/gov/digital/ho/hocs/client/casework/dto/CreateMigrationCaseRequest.java, src/main/java/uk/gov/digital/ho/hocs/client/migration/casework/MigrationCaseworkClient.java, src/main/java/uk/gov/digital/ho/hocs/client/migration/casework/dto/CreateMigrationCaseRequest.java, src/main/java/uk/gov/digital/ho/hocs/client/migration/casework/dto/CreateMigrationCaseResponse.java, src/main/java/uk/gov/digital/ho/hocs/queue/common/MessageValidator.java, src/main/java/uk/gov/digital/ho/hocs/queue/common/MigrationQueueListener.java, src/main/java/uk/gov/digital/ho/hocs/queue/common/QueueListener.java, src/main/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintValidator.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationCaseTypeData.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationData.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationMessageHandler.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationMessageValidator.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationService.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationValidator.java, src/main/resources/application-local.yml, src/test/java/uk/gov/digital/ho/hocs/client/migration/casework/MigrationCaseworkClientTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/integration/AwsSqsIntegrationTestBase.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/integration/MigrationQueueListenerIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/complaints/ukvi/UKVIComplaintValidatorTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/migration/MigrationServiceTest.java, src/test/resources/validMigration.json
Include migration schema.
Validate migration message received.
Prepare migration request and call new migration endpoint on casework.
=> Create migration case

README.md
Update the README to contain a paragraph around the requirement to have the schemas published to Maven Local.
=> :memo: Update README contents

.drone.yml
This was taking too long to start up and pass healthcheck.
=> HOCS-5561: remove 'too low' cpu limit

src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationCaseService.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationCaseTypeData.java, src/main/java/uk/gov/digital/ho/hocs/queue/migration/MigrationService.java, src/test/java/uk/gov/digital/ho/hocs/queue/common/integration/MigrationQueueListenerIntegrationTest.java, src/test/java/uk/gov/digital/ho/hocs/queue/migration/MigrationServiceTest.java, src/test/resources/validMigrationBF.json, src/test/resources/validMigrationCOMP.json, src/test/resources/validMigrationIEDET.json, src/test/resources/validMigrationPOGR.json
Take case type from migration message and add it to casework request for each case.
=> HOCS-6017: Map cases to correct Case Type

.drone.yml, README.md, src/main/java/uk/gov/digital/ho/hocs/application/aws/SqsConfiguration.java, src/main/java/uk/gov/digital/ho/hocs/application/aws/SqsMessageListenerContainerFactory.java, src/main/java/uk/gov/digital/ho/hocs/entrypoint/MigrationQueueListener.java, src/main/java/uk/gov/digital/ho/hocs/entrypoint/UkviQueueListener.java, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/java/uk/gov/digital/ho/hocs/entrypoint/integration/AwsSqsIntegrationTestBase.java, src/test/java/uk/gov/digital/ho/hocs/entrypoint/integration/MigrationQueueListenerIntegrationTest.java
This change standardises the queue properties to enable the service to listen to a single queue.
=> Standardise queue properties

build.gradle, src/main/resources/config/enum-mappings.json, src/test/java/uk/gov/digital/ho/hocs/domain/queue/complaints/ComplaintServiceTest.java, src/test/java/uk/gov/digital/ho/hocs/domain/queue/complaints/ukvi/UKVIComplaintDataTest.java, src/test/resources/webform/staffBehaviour.json
Rollback the schema version as the callee side is running this version and not 1.3.2.
=> HOCS-6629: rollback schema version

src/test/resources/migration/validMigrationTO.json
HOCS-6648:Separate json file to create TO closed case.
=> HOCS-6648:Separate json file to create TO closed case

src/main/java/uk/gov/digital/ho/hocs/entrypoint/CsvHelpers.java, src/main/java/uk/gov/digital/ho/hocs/entrypoint/model/CaseDataCsvInputRow.java, src/main/java/uk/gov/digital/ho/hocs/entrypoint/model/CaseDataCsvOutputRow.java
* Handle null dates
* Skip empty CSV lines
https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-6764
=> [HOCS-6764] Empty CSV lines cause cryptic NPE errors

build.gradle
1. jar version updates for springboot3
2. All junit tests passed
3. Tested locally and process came up without any errors.
=> jar version updates for springboot3
